name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install App Dependencies
      run: npm install

    - name: Execute Unit Tests
      run: npm run test:unit

    - name: Display SoftUni Username
      run: echo HeliXs66

  run-ui-tests:
    needs: build-and-unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install App Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Start Application
      run: npm start &

    - name: Execute UI Tests
      run: npm run test:ui

  deploy-to-render:
    needs: run-ui-tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}